language: php

php:
  - 7.2
  
env:
  - RHOTEST=unit
  - RHOTEST=integration

before_install:
  - echo | pecl install channel://pecl.php.net/yaml-2.0.0
  - if [[ "$RHOTEST" == "unit" ]]; then travis_retry make dev-env; fi
  - if [[ "$RHOTEST" == "integration" ]]; then travis_retry make no-dev-env; fi
  - travis_retry composer dump-autoload # Dumps autoload-dev too 
  - cat vendor/composer/autoload_psr4.php

before_script:
  - make build

script:
  - make "$RHOTEST"-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
